services:
  - type: web
    name: zn98-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zn98-postgres
          property: connectionString
      - key: PORT
        value: 3000

databases:
  - name: zn98-postgres
    ipAllowList: []